[phases.setup]
aptPkgs = ['python3', 'python3-pip', 'build-essential', 'python3-venv']

[phases.install]
cmds = [
  'python -m venv /opt/venv',
  '. /opt/venv/bin/activate && pip install -r requirements.txt'
]

[start]
cmd = 'python run.py'